### ISSUE TITLE
Recording in ARKit with iPad

### ISSUE THREAD

**Issue by frank-1992** [gorastudio-git/SCNRecorder#60]
When I use ipad to record ARKit SCNView, the picture is not normal and the size is wrong
You can see the picture here, 
The first picture is the screen display
[https://1drv.ms/u/s!AmpfcHWI3MLhanf1KCXPFdlZMus?e=KZ8Z5M](url)
The second picture is the capture result
[https://1drv.ms/u/s!AmpfcHWI3MLha_BwTAUGmCHfbxI?e=z17XLb](url)

Are there any settings that need to be modified when using iPad to capture?

Thank you.

**Comment by frank-1992** [comment]
Now , I have solved it

**Comment by frank-1992** [comment]
Can someone help me? Another problem, when I play the video recorded by iPAD on Windows PC, the video rotate 90 and mirror @gorastudio-ceo

**Comment by v-grigoriev** [comment]
What player do you use on Windows?Can you try something like vlc?Vladislav GrigoryevOn 30 Mar 2023, at 9:04 AM, frank ***@***.***> wrote:﻿
Can someone help me? Another problem, when I play the video recorded by iPAD on Windows PC, the video rotate 90 and mirror @gorastudio-ceo

**Comment by frank-1992** [comment]
> What player do you use on Windows?Can you try something like vlc?Vladislav GrigoryevOn 30 Mar 2023, at 9:04 AM, frank ***@***.***> wrote:﻿ Can someone help me? Another problem, when I play the video recorded by iPAD on Windows PC, the video rotate 90 and mirror @gorastudio-ceo —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

In fact, there are two problems. Use ARScnView to record video and take pictures on the ipad. The direction of the video and the display of the screen are wrong.
Another problem is that even if you change your code so that the ipad recording video looks correct, when the video is uploaded to the windows pc, it will be mirrored with any player, and some will even be rotated and mirrored

**Comment by frank-1992** [comment]
@gorastudio-ceo hi, can you help to try this on iPad? I think there are some issues. Thank you
