### ISSUE TITLE
extension macro cannot be attached to property ('error')

### ISSUE THREAD

**Issue by rahveekotadiya** [gorastudio-git/SCNRecorder#66]
I recently updated the pod in my project, and I'm now encountering an error. I've attached a screenshot for your reference. 
<img width="927" alt="Screenshot 2024-09-23 at 4 33 21 PM" src="https://github.com/user-attachments/assets/1d9980d7-bbf8-4744-aa56-9953cc3cbff9">

**Comment by MarsVard** [comment]
@rahveekotadiya Did you find a fix?

**Comment by v-grigoriev** [comment]
It's already fixed on master. 

But I can't find time to release it.

**Comment by MarsVard** [comment]
Thanks for the hard work! I imported it as a package dependency from github

**Comment by nikhileshkapdi** [comment]
@v-grigoriev can you explain how can I use master I can't get it resolved. can you please help me

**Comment by v-grigoriev** [comment]
@nikhileshkapdi  New version is available, please check it https://github.com/CocoaPods/Specs/blob/master/Specs/3/2/e/SCNRecorder/2.9.0/SCNRecorder.podspec.json
