### ISSUE TITLE
Xcode 16 building errors

### ISSUE THREAD

**Issue by ozgurshn** [gorastudio-git/SCNRecorder#68]
Hello, thanks for this awesome repo, we were using it in our app but lately with Xcode 16 this errors. It occurs with SDK SCNRecorder (2.8.1) Could you guys guide me how to fix these errors?
<img width="627" alt="image" src="https://github.com/user-attachments/assets/6697e8a4-9612-4639-a314-4dd60042eb36">

**Comment by tarrouye** [comment]
Hey @ozgurshn  this issue is already fixed on master but there hasn't been a new release. Changing your package dependency to use branch `master` instead of release versioning should fix this for you.

**Comment by ozgurshn** [comment]
Hey @tarrouye thank you for the guidance.
